/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectopoo2;

import controller.EmpleadoController;
import controller.UsuarioController;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Empleado;
import model.Usuario;

/**
 *
 * @author CHRISTOPHER
 */
public class FrmUsuario extends javax.swing.JFrame {
    private DefaultTableModel dtmEmpleado = new DefaultTableModel();
    private EmpleadoController empController = new EmpleadoController();
    private DefaultTableModel dtmUsuario = new DefaultTableModel();
    private UsuarioController usuController = new UsuarioController();
    /**
     * Creates new form FrmUsuario
     */
    public FrmUsuario() {
        initComponents();
        columnaEmp();
        listarEmp();
        columnaUsu();
        listarUsu();
        this.setLocationRelativeTo(null);
    }

    public void columnaEmp()
    {
        dtmEmpleado.addColumn("CODIGO");
        dtmEmpleado.addColumn("NONBRE");
        dtmEmpleado.addColumn("APELLIDO");
        dtmEmpleado.addColumn("DNI");
        dtmEmpleado.addColumn("TELEFONO");
        dtmEmpleado.addColumn("SEXO");
        this.GrillaEmp.setModel(dtmEmpleado);
    }
    
    public void columnaUsu()
    {
        dtmUsuario.addColumn("CODIGO");
        dtmUsuario.addColumn("EMPLEADO");
        dtmUsuario.addColumn("USUARIO");
        dtmUsuario.addColumn("CONTRASEÑA");
        this.GrillaUsu.setModel(dtmUsuario);
    }
     
    public void listarEmp()
    {
        List<Empleado> lst = empController.getAllEmpleadoController();
        dtmEmpleado.setNumRows(0);
        for(Empleado x:lst)
        {
            Object[] vector = new Object[6];
            vector[0] = x.getIdEmp();
            vector[1] = x.getNomEmp();
            vector[2] = x.getApeEmp();
            vector[3] = x.getDniEmp();
            vector[4] = x.getTlfEmp();
            vector[5] = x.getSexoEmp();
            dtmEmpleado.addRow(vector);
        }
        GrillaEmp.setModel(dtmEmpleado);
    }
    
    public void listarUsu()
    {
        List<Usuario> lst = usuController.getAllUsuarioController();
        dtmUsuario.setNumRows(0);
        for(Usuario x:lst)
        {
            Object[] vector = new Object[4];
            vector[0] = x.getIdUsu();
            vector[1] = x.getIdEmpUsu();
            vector[2] = x.getNomUsu();
            vector[3] = x.getPassUsu();
            dtmUsuario.addRow(vector);
        }
        GrillaUsu.setModel(dtmUsuario);
    }
    
    public void limpiarEmp()
    {
        this.txtCodEmp.setText("");
        this.txtNomEmp.setText("");
        this.txtApeEmp.setText("");
        this.txtDniEmp.setText("");
        this.txtTlfEmp.setText("");
        this.cmbSexoEmp.setSelectedIndex(0);
    }
    
    public void limpiarUsu()
    {
        this.txtCodUsu.setText("");
        FrmUsuario.txtCodEmpUsu.setText("");
        this.txtUsuario.setText("");
        this.txtPassUsu.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCodEmp = new javax.swing.JTextField();
        txtNomEmp = new javax.swing.JTextField();
        txtApeEmp = new javax.swing.JTextField();
        txtDniEmp = new javax.swing.JTextField();
        txtTlfEmp = new javax.swing.JTextField();
        cmbSexoEmp = new javax.swing.JComboBox<>();
        btnAgregarEmp = new javax.swing.JButton();
        btnNuevoEmp = new javax.swing.JButton();
        btnEliminarEmp = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        GrillaEmp = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txtBuscarEmp = new javax.swing.JTextField();
        btnActualizarEmp = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtPassUsu = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtCodUsu = new javax.swing.JTextField();
        btnAgregarUsu = new javax.swing.JButton();
        btnEliminarUsu = new javax.swing.JButton();
        btnActualizarUsu = new javax.swing.JButton();
        btnNuevoUsu = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        GrillaUsu = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        txtBuscarUsu = new javax.swing.JTextField();
        btnVistaEmp = new javax.swing.JButton();
        txtCodEmpUsu = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(0, 51, 153));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Bodoni MT Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DIXIS");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(37, 37, 37))
        );

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel9.setBackground(new java.awt.Color(102, 102, 102));

        jLabel23.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("USUARIO");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(330, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addGap(250, 250, 250))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel23)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 800, 120));

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        jButton5.setBackground(new java.awt.Color(102, 102, 102));
        jButton5.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Christopher\\Documents\\NetBeansProjects\\proyectopoo2\\src\\main\\java\\com\\mycompany\\proyectopoo2\\Img\\agregar usuario.png")); // NOI18N
        jButton5.setText("Nuevo empleado");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(102, 102, 102));
        jButton6.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Christopher\\Documents\\NetBeansProjects\\proyectopoo2\\src\\main\\java\\com\\mycompany\\proyectopoo2\\Img\\agregar usuario.png")); // NOI18N
        jButton6.setText("Nuevo usuario");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        btnCerrar.setBackground(new java.awt.Color(102, 102, 102));
        btnCerrar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(204, 0, 51));
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jButton5)
                .addGap(77, 77, 77)
                .addComponent(jButton6)
                .addGap(75, 75, 75)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 200, -1));

        jLabel2.setText("Código:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Apellido:");

        jLabel5.setText("DNI:");

        jLabel6.setText("Teléfono:");

        jLabel7.setText("Sexo:");

        txtCodEmp.setEditable(false);

        txtNomEmp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomEmpKeyTyped(evt);
            }
        });

        txtApeEmp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApeEmpKeyTyped(evt);
            }
        });

        txtDniEmp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDniEmpKeyTyped(evt);
            }
        });

        txtTlfEmp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTlfEmpKeyTyped(evt);
            }
        });

        cmbSexoEmp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "H", "M"}));

        btnAgregarEmp.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnAgregarEmp.setForeground(new java.awt.Color(0, 0, 204));
        btnAgregarEmp.setText("Agregar");
        btnAgregarEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEmpActionPerformed(evt);
            }
        });

        btnNuevoEmp.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnNuevoEmp.setForeground(new java.awt.Color(0, 0, 204));
        btnNuevoEmp.setText("Nuevo");
        btnNuevoEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoEmpActionPerformed(evt);
            }
        });

        btnEliminarEmp.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnEliminarEmp.setForeground(new java.awt.Color(0, 0, 204));
        btnEliminarEmp.setText("Eliminar");
        btnEliminarEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEmpActionPerformed(evt);
            }
        });

        GrillaEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        GrillaEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GrillaEmpMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(GrillaEmp);

        jLabel8.setText("Nombre:");

        txtBuscarEmp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarEmpKeyReleased(evt);
            }
        });

        btnActualizarEmp.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnActualizarEmp.setForeground(new java.awt.Color(0, 0, 204));
        btnActualizarEmp.setText("Modificar");
        btnActualizarEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarEmpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodEmp)
                            .addComponent(txtNomEmp)
                            .addComponent(txtApeEmp)
                            .addComponent(txtDniEmp)
                            .addComponent(txtTlfEmp)
                            .addComponent(cmbSexoEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregarEmp)
                            .addComponent(btnEliminarEmp))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnActualizarEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNuevoEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscarEmp)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtBuscarEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtCodEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNomEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtApeEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtDniEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtTlfEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbSexoEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregarEmp)
                            .addComponent(btnNuevoEmp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEliminarEmp)
                            .addComponent(btnActualizarEmp))))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Empleado", jPanel2);

        jLabel9.setText("Código:");

        jLabel10.setText("Empleado:");

        jLabel11.setText("Usuario:");

        jLabel12.setText("Pass:");

        txtCodUsu.setEditable(false);

        btnAgregarUsu.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnAgregarUsu.setForeground(new java.awt.Color(0, 0, 204));
        btnAgregarUsu.setText("Agregar");
        btnAgregarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarUsuActionPerformed(evt);
            }
        });

        btnEliminarUsu.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnEliminarUsu.setForeground(new java.awt.Color(0, 0, 204));
        btnEliminarUsu.setText("Eliminar");
        btnEliminarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarUsuActionPerformed(evt);
            }
        });

        btnActualizarUsu.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnActualizarUsu.setForeground(new java.awt.Color(0, 0, 204));
        btnActualizarUsu.setText("Modificar");
        btnActualizarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarUsuActionPerformed(evt);
            }
        });

        btnNuevoUsu.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnNuevoUsu.setForeground(new java.awt.Color(0, 0, 204));
        btnNuevoUsu.setText("Nuevo");
        btnNuevoUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoUsuActionPerformed(evt);
            }
        });

        GrillaUsu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        GrillaUsu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GrillaUsuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(GrillaUsu);

        jLabel13.setText("Usuario");

        txtBuscarUsu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarUsuKeyReleased(evt);
            }
        });

        btnVistaEmp.setText("...");
        btnVistaEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVistaEmpActionPerformed(evt);
            }
        });

        txtCodEmpUsu.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEliminarUsu)
                            .addComponent(btnAgregarUsu))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnActualizarUsu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNuevoUsu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPassUsu, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodUsu))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(36, 36, 36)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(txtCodEmpUsu))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVistaEmp)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscarUsu)))
                .addGap(19, 19, 19))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtBuscarUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(btnVistaEmp)
                            .addComponent(txtCodEmpUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtPassUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(91, 91, 91)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregarUsu)
                            .addComponent(btnNuevoUsu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEliminarUsu)
                            .addComponent(btnActualizarUsu)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Usuario", jPanel3);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 800, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnAgregarEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEmpActionPerformed
        if(!this.txtCodEmp.getText().isEmpty() && !this.txtNomEmp.getText().isEmpty() &&
           !this.txtApeEmp.getText().isEmpty() && !this.txtDniEmp.getText().isEmpty() &&
           !this.txtTlfEmp.getText().isEmpty())
        {
           int msg = JOptionPane.showConfirmDialog(this.btnAgregarEmp,"Deseas Guardar el Registro!!!","Guardar",JOptionPane.YES_NO_OPTION);
            if (msg == JOptionPane.YES_OPTION)
            {
                Empleado emp = new Empleado();
                emp.setIdEmp(this.txtCodEmp.getText());
                emp.setNomEmp(this.txtNomEmp.getText());
                emp.setApeEmp(this.txtApeEmp.getText());
                emp.setDniEmp(this.txtDniEmp.getText());
                emp.setTlfEmp(this.txtTlfEmp.getText());
                emp.setSexoEmp(this.cmbSexoEmp.getSelectedItem().toString());
                empController.addEmpleadoController(emp);
                listarEmp();//Actualizar la BD
                limpiarEmp();
                JOptionPane.showMessageDialog(this,"Registro Guardado Satisfactoriamente");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Llene todos los recuadros");
        }
    }//GEN-LAST:event_btnAgregarEmpActionPerformed

    private void btnEliminarEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEmpActionPerformed
        if(!this.txtCodEmp.getText().isEmpty() && !this.txtNomEmp.getText().isEmpty() &&
           !this.txtApeEmp.getText().isEmpty() && !this.txtDniEmp.getText().isEmpty() &&
           !this.txtTlfEmp.getText().isEmpty())
        {
            int msg = JOptionPane.showConfirmDialog(this.btnEliminarEmp,"Deseas Eliminar el Registro!!!","Eliminar",JOptionPane.YES_NO_OPTION);
            if (msg == JOptionPane.YES_OPTION)
            {
                Empleado emp = new Empleado();
                emp.setIdEmp(this.txtCodEmp.getText());
                empController.removeEmpleadoController(emp);
                listarEmp();//Actualizar la BD
                limpiarEmp();
                JOptionPane.showMessageDialog(this,"Registro Eliminado Satisfactoriamente");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Por favor de un click al empleado a eliminar en la grilla");
        }
    }//GEN-LAST:event_btnEliminarEmpActionPerformed

    private void btnActualizarEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarEmpActionPerformed
        if(!this.txtCodEmp.getText().isEmpty() && !this.txtNomEmp.getText().isEmpty() &&
           !this.txtApeEmp.getText().isEmpty() && !this.txtDniEmp.getText().isEmpty() &&
           !this.txtTlfEmp.getText().isEmpty())
        {
            int msg = JOptionPane.showConfirmDialog(this.btnEliminarEmp,"Deseas Eliminar el Registro!!!","Eliminar",JOptionPane.YES_NO_OPTION);
            if (msg == JOptionPane.YES_OPTION)
            {
                Empleado emp = new Empleado();
                emp.setIdEmp(this.txtCodEmp.getText());
                emp.setNomEmp(this.txtNomEmp.getText());
                emp.setApeEmp(this.txtApeEmp.getText());
                emp.setDniEmp(this.txtDniEmp.getText());
                emp.setTlfEmp(this.txtTlfEmp.getText());
                emp.setSexoEmp(this.cmbSexoEmp.getSelectedItem().toString());
                empController.updateEmpleadoController(emp);
                listarEmp();//Actualizar la BD
                limpiarEmp();
                JOptionPane.showMessageDialog(this,"Registro Eliminado Satisfactoriamente");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Por favor de un click al empleado a modificar en la grilla");
        }
    }//GEN-LAST:event_btnActualizarEmpActionPerformed

    private void GrillaEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrillaEmpMouseClicked
        this.txtCodEmp.setText(GrillaEmp.getValueAt(GrillaEmp.getSelectedRow(), 0).toString());
        this.txtNomEmp.setText(GrillaEmp.getValueAt(GrillaEmp.getSelectedRow(), 1).toString());
        this.txtApeEmp.setText(GrillaEmp.getValueAt(GrillaEmp.getSelectedRow(), 2).toString());
        this.txtDniEmp.setText(GrillaEmp.getValueAt(GrillaEmp.getSelectedRow(), 3).toString());
        this.txtTlfEmp.setText(GrillaEmp.getValueAt(GrillaEmp.getSelectedRow(), 4).toString());
        this.cmbSexoEmp.setSelectedItem(GrillaEmp.getValueAt(GrillaEmp.getSelectedRow(), 5));
    }//GEN-LAST:event_GrillaEmpMouseClicked

    private void btnNuevoEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoEmpActionPerformed
        this.txtCodEmp.setText(empController.getCorrelativoEmpleadoController());
        this.txtNomEmp.setText("");
        this.txtApeEmp.setText("");
        this.txtDniEmp.setText("");
        this.txtTlfEmp.setText("");
        this.cmbSexoEmp.setSelectedIndex(0);
    }//GEN-LAST:event_btnNuevoEmpActionPerformed

    private void txtBuscarEmpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarEmpKeyReleased
        Empleado obj = new Empleado();
        obj.setNomEmp(this.txtBuscarEmp.getText());
        List<Empleado> lst = empController.getBuscarNombreEmpleadoController(obj);
        dtmEmpleado.setNumRows(0);
        for(Empleado x:lst)
        {
            Object[] vector = new Object[6];
            vector[0] = x.getIdEmp();
            vector[1] = x.getNomEmp();
            vector[2] = x.getApeEmp();
            vector[3] = x.getDniEmp();
            vector[4] = x.getTlfEmp();
            vector[5] = x.getSexoEmp();
            dtmEmpleado.addRow(vector);
        }
        GrillaEmp.setModel(dtmEmpleado);
    }//GEN-LAST:event_txtBuscarEmpKeyReleased

    private void txtNomEmpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomEmpKeyTyped
        Character c = evt.getKeyChar();
        
        if(!Character.isLetter(c) && c != KeyEvent.VK_SPACE)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtNomEmpKeyTyped

    private void txtApeEmpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApeEmpKeyTyped
        Character c = evt.getKeyChar();
        
        if(!Character.isLetter(c) && c != KeyEvent.VK_SPACE)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtApeEmpKeyTyped

    private void txtDniEmpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniEmpKeyTyped
        Character c = evt.getKeyChar();
        
        if(!Character.isDigit(c) || this.txtDniEmp.getText().length() >= 8)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtDniEmpKeyTyped

    private void txtTlfEmpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTlfEmpKeyTyped
        Character c = evt.getKeyChar();
        
        if(!Character.isDigit(c) || this.txtTlfEmp.getText().length() >= 9)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtTlfEmpKeyTyped

    private void btnAgregarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarUsuActionPerformed
        if(!this.txtCodUsu.getText().isEmpty() && !FrmUsuario.txtCodEmpUsu.getText().isEmpty() &&
           !this.txtUsuario.getText().isEmpty() && !this.txtPassUsu.getText().isEmpty())
        {
            int msg = JOptionPane.showConfirmDialog(this.btnAgregarUsu,"Deseas Guardar el Registro!!!","Guardar",JOptionPane.YES_NO_OPTION);
            if (msg == JOptionPane.YES_OPTION)
            {
                Usuario usu = new Usuario();
                usu.setIdUsu(Integer.parseInt(this.txtCodUsu.getText()));
                usu.setIdEmpUsu(txtCodEmpUsu.getText());
                usu.setNomUsu(this.txtUsuario.getText());
                usu.setPassUsu(this.txtPassUsu.getText());
                usuController.addUsuarioController(usu);
                listarUsu();//Actualizar la BD
                limpiarUsu();
                JOptionPane.showMessageDialog(this,"Registro Guardado Satisfactoriamente");
            }
        }
         else
        {
            JOptionPane.showMessageDialog(this,"Llene todos los recuadros");
        }
    }//GEN-LAST:event_btnAgregarUsuActionPerformed

    private void btnNuevoUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoUsuActionPerformed
        this.txtCodUsu.setText(String.valueOf(usuController.getCorrelativoUsuarioController()));
        FrmUsuario.txtCodEmpUsu.setText("");
        this.txtUsuario.setText("");
        this.txtPassUsu.setText("");
    }//GEN-LAST:event_btnNuevoUsuActionPerformed

    private void btnEliminarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarUsuActionPerformed
        if(!this.txtCodUsu.getText().isEmpty() && !FrmUsuario.txtCodEmpUsu.getText().isEmpty() &&
           !this.txtUsuario.getText().isEmpty() && !this.txtPassUsu.getText().isEmpty())
        {
            int msg = JOptionPane.showConfirmDialog(this.btnEliminarUsu,"Deseas Eliminar el Registro!!!","Eliminar",JOptionPane.YES_NO_OPTION);
            if (msg == JOptionPane.YES_OPTION)
            {
                Usuario usu = new Usuario();
                usu.setIdUsu(Integer.parseInt(this.txtCodUsu.getText()));
                usuController.removeUsuarioController(usu);
                listarUsu();//Actualizar la BD
                limpiarUsu();
                JOptionPane.showMessageDialog(this,"Registro Eliminado Satisfactoriamente");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Por favor de un click al usuario a eliminar en la grilla");
        }
    }//GEN-LAST:event_btnEliminarUsuActionPerformed

    private void btnActualizarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarUsuActionPerformed
        if(!this.txtCodUsu.getText().isEmpty() && !FrmUsuario.txtCodEmpUsu.getText().isEmpty() &&
           !this.txtUsuario.getText().isEmpty() && !this.txtPassUsu.getText().isEmpty())
        {
            int msg = JOptionPane.showConfirmDialog(this.btnActualizarUsu,"Deseas Actualizar el Registro!!!","Actualizar",JOptionPane.YES_NO_OPTION);
            if (msg == JOptionPane.YES_OPTION)
            {
                Usuario usu = new Usuario();
                usu.setIdUsu(Integer.parseInt(this.txtCodUsu.getText()));
                usu.setIdEmpUsu(FrmUsuario.txtCodEmpUsu.getText());
                usu.setNomUsu(this.txtUsuario.getText());
                usu.setPassUsu(this.txtPassUsu.getText());
                usuController.updateUsuarioController(usu);
                listarUsu();//Actualizar la BD
                limpiarUsu();
                JOptionPane.showMessageDialog(this,"Registro Actualizado Satisfactoriamente");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Por favor de un click al usuario a eliminar en la grilla");
        }
    }//GEN-LAST:event_btnActualizarUsuActionPerformed

    private void txtBuscarUsuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarUsuKeyReleased
        Usuario obj = new Usuario();
        obj.setNomUsu(this.txtBuscarUsu.getText());
        List<Usuario> lst = usuController.getBuscarPorCorreoUsuarioController(obj);
        dtmUsuario.setNumRows(0);
        for(Usuario x:lst)
        {
            Object[] vector = new Object[4];
            vector[0] = x.getIdUsu();
            vector[1] = x.getIdEmpUsu();
            vector[2] = x.getNomUsu();
            vector[3] = x.getPassUsu();
            dtmUsuario.addRow(vector);
        }
        GrillaUsu.setModel(dtmUsuario);
    }//GEN-LAST:event_txtBuscarUsuKeyReleased

    private void GrillaUsuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrillaUsuMouseClicked
        this.txtCodUsu.setText(GrillaUsu.getValueAt(GrillaUsu.getSelectedRow(), 0).toString());
        FrmUsuario.txtCodEmpUsu.setText(GrillaUsu.getValueAt(GrillaUsu.getSelectedRow(), 1).toString());
        this.txtUsuario.setText(GrillaUsu.getValueAt(GrillaUsu.getSelectedRow(), 2).toString());
        this.txtPassUsu.setText(GrillaUsu.getValueAt(GrillaUsu.getSelectedRow(), 3).toString());
    }//GEN-LAST:event_GrillaUsuMouseClicked

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnVistaEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVistaEmpActionPerformed
        FrmVistaEmpleado frmEmp = new FrmVistaEmpleado();
        frmEmp.toFront();
        frmEmp.setVisible(true);
        frmEmp.opcion = 1;
    }//GEN-LAST:event_btnVistaEmpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable GrillaEmp;
    private javax.swing.JTable GrillaUsu;
    private javax.swing.JButton btnActualizarEmp;
    private javax.swing.JButton btnActualizarUsu;
    private javax.swing.JButton btnAgregarEmp;
    private javax.swing.JButton btnAgregarUsu;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEliminarEmp;
    private javax.swing.JButton btnEliminarUsu;
    private javax.swing.JButton btnNuevoEmp;
    private javax.swing.JButton btnNuevoUsu;
    private javax.swing.JButton btnVistaEmp;
    private javax.swing.JComboBox<String> cmbSexoEmp;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtApeEmp;
    private javax.swing.JTextField txtBuscarEmp;
    private javax.swing.JTextField txtBuscarUsu;
    private javax.swing.JTextField txtCodEmp;
    public static javax.swing.JTextField txtCodEmpUsu;
    private javax.swing.JTextField txtCodUsu;
    private javax.swing.JTextField txtDniEmp;
    private javax.swing.JTextField txtNomEmp;
    private javax.swing.JTextField txtPassUsu;
    private javax.swing.JTextField txtTlfEmp;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
