/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectopoo2;

import controller.EmpleadoController;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Empleado;

/**
 *
 * @author CHRISTOPHER
 */
public class FrmVistaEmpleado extends javax.swing.JFrame {
    private DefaultTableModel dtmEmpleado = new DefaultTableModel();
    private EmpleadoController empController = new EmpleadoController();
    public byte opcion;
    /**
     * Creates new form FrmVistaEmpleado
     */
    public FrmVistaEmpleado() {
        initComponents();
        columnaEmp();
        listarEmp();
        this.setLocationRelativeTo(null);
    }
    
    public void columnaEmp()
    {
        dtmEmpleado.addColumn("CODIGO");
        dtmEmpleado.addColumn("NONBRE");
        dtmEmpleado.addColumn("APELLIDO");
        dtmEmpleado.addColumn("DNI");
        dtmEmpleado.addColumn("TELEFONO");
        dtmEmpleado.addColumn("SEXO");
        this.GrillaEmp.setModel(dtmEmpleado);
    }
    
    public void listarEmp()
    {
        List<Empleado> lst = empController.getAllEmpleadoController();
        dtmEmpleado.setNumRows(0);
        for(Empleado x:lst)
        {
            Object[] vector = new Object[6];
            vector[0] = x.getIdEmp();
            vector[1] = x.getNomEmp();
            vector[2] = x.getApeEmp();
            vector[3] = x.getDniEmp();
            vector[4] = x.getTlfEmp();
            vector[5] = x.getSexoEmp();
            dtmEmpleado.addRow(vector);
        }
        GrillaEmp.setModel(dtmEmpleado);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        GrillaEmp = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtBuscarEmp = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setText("LISTA DE EMPLEADOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(197, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(17, 17, 17))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));

        GrillaEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        GrillaEmp.setEditingColumn(0);
        GrillaEmp.setEditingRow(0);
        GrillaEmp.setFocusable(false);
        GrillaEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GrillaEmpMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(GrillaEmp);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");

        txtBuscarEmp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarEmpKeyReleased(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscarEmp)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalir)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBuscarEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GrillaEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrillaEmpMouseClicked
        if(opcion == 1)
        {
            if(evt.getClickCount() == 1)
            {
                int fila = GrillaEmp.getSelectedRow();
                FrmUsuario.txtCodEmpUsu.setText(GrillaEmp.getValueAt(fila, 0).toString());
                dispose();
            }
        }
        else if(opcion == 2)
        {
            if(evt.getClickCount() == 1)
            {
                int fila = GrillaEmp.getSelectedRow();
                FrmVenta.txtIdUsuVenta.setText(GrillaEmp.getValueAt(fila, 0).toString());
                FrmVenta.txtNomUsuVenta.setText(GrillaEmp.getValueAt(fila, 1).toString() + " " + GrillaEmp.getValueAt(fila, 2).toString());
                dispose();
            }
        }
        else if(opcion == 3)
        {
            if(evt.getClickCount() == 1)
            {
                int fila = GrillaEmp.getSelectedRow();
                FrmCompra.txtCodEmpCompra.setText(GrillaEmp.getValueAt(fila, 0).toString());
                FrmCompra.txtNomEmpCompra.setText(GrillaEmp.getValueAt(fila, 1).toString());
                dispose();
            }
        }
    }//GEN-LAST:event_GrillaEmpMouseClicked

    private void txtBuscarEmpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarEmpKeyReleased
        Empleado obj = new Empleado();
        obj.setNomEmp(this.txtBuscarEmp.getText());
        List<Empleado> lst = empController.getBuscarNombreEmpleadoController(obj);
        dtmEmpleado.setNumRows(0);
        for(Empleado x:lst)
        {
            Object[] vector = new Object[6];
            vector[0] = x.getIdEmp();
            vector[1] = x.getNomEmp();
            vector[2] = x.getApeEmp();
            vector[3] = x.getDniEmp();
            vector[4] = x.getTlfEmp();
            vector[5] = x.getSexoEmp();
            dtmEmpleado.addRow(vector);
        }
        GrillaEmp.setModel(dtmEmpleado);
    }//GEN-LAST:event_txtBuscarEmpKeyReleased

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVistaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVistaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVistaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVistaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVistaEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable GrillaEmp;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBuscarEmp;
    // End of variables declaration//GEN-END:variables
}
