/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectopoo2;

import controller.ProductoController;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Producto;

/**
 *
 * @author CHRISTOPHER
 */
public class FrmVistaProducto extends javax.swing.JFrame {
    private DefaultTableModel dtmProducto = new DefaultTableModel();
    private ProductoController prodController = new ProductoController();
    public byte opcion;
    /**
     * Creates new form FrmVistaProducto
     */
    public FrmVistaProducto() {
        initComponents();
        columnaProd();
        listarProd();
        this.setLocationRelativeTo(null);
    }
    
    public void columnaProd()
    {
        dtmProducto.addColumn("CODIGO");
        dtmProducto.addColumn("PROVEEDOR");
        dtmProducto.addColumn("NOMBRE");
        dtmProducto.addColumn("PRECIO COMPRA");
        dtmProducto.addColumn("PRECIO VENTA");
        dtmProducto.addColumn("CANTIDAD");
        this.GrillaProducto.setModel(dtmProducto);
    }
        
    public void listarProd()
    {
        List<Producto> lst = prodController.getAllProductoController();
        dtmProducto.setNumRows(0);
        for(Producto x:lst)
        {
            Object[] vector = new Object[6];
            vector[0] = x.getIdProd();
            vector[1] = x.getIdProv();
            vector[2] = x.getNomProd();
            vector[3] = x.getPreComProd();
            vector[4] = x.getPreVenProd();
            vector[5] = x.getCantidad();
            dtmProducto.addRow(vector);
        }
        GrillaProducto.setModel(dtmProducto);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        GrillaProducto = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtBuscarProducto = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setText("LISTA DE PRODUCTOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(197, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(17, 17, 17))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));

        GrillaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        GrillaProducto.setEditingColumn(0);
        GrillaProducto.setEditingRow(0);
        GrillaProducto.setFocusable(false);
        GrillaProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GrillaProductoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(GrillaProducto);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Descripcion:");

        txtBuscarProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarProductoKeyReleased(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscarProducto)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalir)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GrillaProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrillaProductoMouseClicked
        if(opcion == 1)
        {
            if(evt.getClickCount() == 1)
            {
                int fila = GrillaProducto.getSelectedRow();
                FrmCompra.txtCodProdCompra.setText(GrillaProducto.getValueAt(fila, 0).toString());
                FrmCompra.txtDesCompra.setText(GrillaProducto.getValueAt(fila, 2).toString());
                FrmCompra.txtPrecioCompra.setText(GrillaProducto.getValueAt(fila, 3).toString());
                FrmCompra.txtIgv.setText(String.valueOf(18));
                dispose();
            }
        }
        else if(opcion == 2)
        {
            if(evt.getClickCount() == 1)
            {
                int fila = GrillaProducto.getSelectedRow();
                FrmVenta.txtCodProdVenta.setText(GrillaProducto.getValueAt(fila, 0).toString());
                FrmVenta.txtDesProdVenta.setText(GrillaProducto.getValueAt(fila, 2).toString());
                FrmVenta.txtPreProdVenta.setText(GrillaProducto.getValueAt(fila, 4).toString());
                FrmVenta.txtStockProdVenta.setText(GrillaProducto.getValueAt(fila, 5).toString());
                FrmVenta.txtIgvVenta.setText(String.valueOf(18));
                dispose();
            }
        }
    }//GEN-LAST:event_GrillaProductoMouseClicked

    private void txtBuscarProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarProductoKeyReleased
        Producto obj = new Producto();
        obj.setNomProd(this.txtBuscarProducto.getText());
        List<Producto> lst = prodController.getBuscarDescripcionProductoController(obj);
        dtmProducto.setNumRows(0);
        for(Producto x:lst)
        {
            Object[] vector = new Object[6];
            vector[0] = x.getIdProd();
            vector[1] = x.getIdProv();
            vector[2] = x.getNomProd();
            vector[3] = x.getPreComProd();
            vector[4] = x.getPreVenProd();
            vector[5] = x.getCantidad();
            dtmProducto.addRow(vector);
        }
        GrillaProducto.setModel(dtmProducto);
    }//GEN-LAST:event_txtBuscarProductoKeyReleased

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVistaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVistaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVistaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVistaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVistaProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable GrillaProducto;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBuscarProducto;
    // End of variables declaration//GEN-END:variables
}
